name: Playwright Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  prepare:
    timeout-minutes: 60
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    outputs:
      playwright-path: ${{ steps.install-deps.outputs.playwright-path }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install Playwright dotenv
        run: npm install dotenv @playwright/test
  run-staging:
    needs: prepare
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Playwright tests on stage
        run: ${{ needs.prepare.outputs.playwright-path }}/npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  run-prod:
    needs: prepare
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Playwright tests on prod
        run: env ENV=Prod ${{ needs.prepare.outputs.playwright-path }}/npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
